services:
  - type: web
    name: ql-diem-backend
    env: docker
    plan: free
    buildCommand: docker build -t ql-diem-backend .
    startCommand: docker run -p 10000:80 ql-diem-backend
    envVars:
      - key: DB_HOST
        value: dpg-cp4k0p8l6cac73b0q0tg-a.oregon-postgres.render.com
      - key: DB_NAME
        value: diemsv_3h0d
      - key: DB_USER
        value: diemsv_3h0d_user
      - key: DB_PASS
        value: 8QJ4QJ4QJ4QJ4QJ4QJ4QJ4QJ4QJ4QJ4 