services:
  - type: web
    name: ql-diem-backend
    env: php
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: dpg-d01kejje5dus73b9pkig-a.singapore-postgres.render.com
      - key: DB_NAME
        value: diemsv_nicy
      - key: DB_USER
        value: minh
      - key: DB_PASS
        value: DyokP4cDfu56PXmA9oARSCSkCPnExvFc 