services:
  - type: web
    name: ql-diem-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: dpg-d01kejje5dus73b9pkig-a.singapore-postgres.render.com
      - key: DB_NAME
        value: diemsv_nicy
      - key: DB_USER
        value: minh
      - key: DB_PASS
        value: DyokP4cDfu56PXmA9oARSCSkCPnExvFc 